version: "3.1"

services:
  db:
    container_name: "postgres_cccat16"
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
